#!/usr/bin/env python3
"""
Learning GLV self/interaction terms from trajectories generated by the three-body scenario.

We reuse the dynamics from `generalized_LV_three_body.py` to generate data,
then train neural parameterizations of the self term and pair term to match the dynamics.
"""
from __future__ import annotations

import argparse
import math
import json
import sys
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.nn.utils import clip_grad_norm_
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from tqdm import tqdm
import numpy as np


@dataclass
class ThreeBodyParams:
    r: torch.Tensor  # (N,)
    A: torch.Tensor  # (N,N)


def get_S(t: torch.Tensor) -> torch.Tensor:
    """
    Sophon coefficient S(t); accepts (...,) tensor of times and returns (..., N).
    """
    base = torch.tensor([0.6, 0.2, 0.7, 0.5, 1.0], dtype=t.dtype, device=t.device)
    det = torch.tensor([1.0, 1.2, 1.0, 1.0, 0.0], dtype=t.dtype, device=t.device)
    return torch.where((t > 180.0)[..., None], det, base)


def get_tau(t: torch.Tensor) -> torch.Tensor:
    """
    Exogenous shock tau(t); accepts (...,) tensor of times and returns (..., N).
    """
    tau = torch.zeros(t.shape + (5,), dtype=t.dtype, device=t.device)
    mask1 = (t >= 20.0) & (t < 70.0)
    tau[mask1, 0] = -0.08
    tau[mask1, 1] = -0.02
    tau[mask1, 3] = 0.05
    mask2 = (t >= 70.0) & (t < 180.0)
    tau[mask2, 0] = 0.05
    tau[mask2, 3] = -0.02
    mask3 = t >= 180.0
    tau[mask3, 0] = 0.02
    tau[mask3, 1] = 0.15
    tau[mask3, 4] = -0.50
    return tau


def rk4_step(f, t, x, dt):
    k1 = f(t, x)
    k2 = f(t + 0.5 * dt, x + 0.5 * dt * k1)
    k3 = f(t + 0.5 * dt, x + 0.5 * dt * k2)
    k4 = f(t + dt, x + dt * k3)
    return x + dt * (k1 + 2 * k2 + 2 * k3 + k4) / 6.0


def simulate_true(params: ThreeBodyParams, X0: torch.Tensor, times: torch.Tensor) -> torch.Tensor:
    def rhs(t_scalar, x_vec):
        if isinstance(t_scalar, torch.Tensor):
            t_tensor = t_scalar.unsqueeze(0)
        else:
            t_tensor = torch.tensor([t_scalar], dtype=x_vec.dtype, device=x_vec.device)
        S = get_S(t_tensor)[0]
        tau = get_tau(t_tensor)[0]
        growth = (params.r * S) + tau
        return x_vec * (growth + params.A @ x_vec)

    states = [X0]
    x = X0
    for i in range(len(times) - 1):
        dt = times[i + 1] - times[i]
        x = rk4_step(rhs, times[i], x, dt)
        x = torch.clamp(x, min=0.0)
        states.append(x)
    return torch.stack(states, dim=0)


class PhiSelf(nn.Module):
    def __init__(self, init_r: torch.Tensor):
        super().__init__()
        noise = torch.rand_like(init_r).clamp_min(1e-3)
        self.log_r = nn.Parameter(torch.log(noise))

    def effective_r(self):
        return torch.exp(self.log_r)

    def forward(self, x, S_vec):
        """
        Inputs:
            x: (...,)
            S_vec: (...,)
        """
        return x * (self.effective_r() * S_vec)


class PhiPair(nn.Module):
    def forward(self, xi, xj):
        return xi * xj


def build_rhs(model_self, model_pair, params: ThreeBodyParams):
    def rhs(t_scalar, x_vec):
        if isinstance(t_scalar, torch.Tensor):
            t_tensor = t_scalar.unsqueeze(0)
        else:
            t_tensor = torch.tensor([t_scalar], dtype=x_vec.dtype, device=x_vec.device)
        S_vec = get_S(t_tensor)[0]
        tau_vec = get_tau(t_tensor)[0]
        phi_s = model_self(x_vec, S_vec) + x_vec * tau_vec

        pair_sum = torch.zeros_like(x_vec)
        for j in range(x_vec.shape[0]):
            pair_val = model_pair(x_vec, x_vec[j].expand_as(x_vec))
            pair_sum += params.A[:, j] * pair_val
        return phi_s + pair_sum

    return rhs


def rollout_model(model_self, model_pair, params: ThreeBodyParams, X0, times):
    rhs = build_rhs(model_self, model_pair, params)
    states = [X0]
    x = X0
    for i in range(len(times) - 1):
        dt = times[i + 1] - times[i]
        x = rk4_step(rhs, times[i], x, dt)
        x = torch.clamp(x, min=0.0)
        states.append(x)
    return torch.stack(states, dim=0)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--steps", type=int, default=300, help="Number of integration steps across [0, t_max].")
    parser.add_argument("--t-max", type=float, default=150.0, help="Maximum simulation horizon.")
    parser.add_argument("--epochs", type=int, default=500)
    parser.add_argument("--lr", type=float, default=5e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="Weight decay for AdamW.")
    parser.add_argument(
        "--grad-clip", type=float, default=1.0, help="Clip gradient norm to this value (<=0 disables clipping)."
    )
    parser.add_argument("--cyclical-max-lr", type=float, default=None, help="Enable CyclicLR with this max LR.")
    parser.add_argument("--cyclical-step", type=int, default=200, help="Step size up for CyclicLR.")
    parser.add_argument(
        "--cosine-min-lr",
        type=float,
        default=None,
        help="Enable CosineAnnealingLR with this minimum learning rate (requires --cosine-tmax).",
    )
    parser.add_argument(
        "--cosine-tmax",
        type=int,
        default=None,
        help="Number of epochs for a cosine annealing cycle (defaults to total epochs if omitted).",
    )
    parser.add_argument("--curriculum-start", type=float, default=5.0, help="Initial training horizon (years).")
    parser.add_argument("--curriculum-increment", type=float, default=1.0, help="Increase in horizon each period.")
    parser.add_argument("--curriculum-period", type=int, default=200, help="Epoch interval before increasing horizon.")
    parser.add_argument(
        "--curriculum-auto",
        action="store_true",
        help="Only increase horizon when loss <= curriculum-threshold instead of fixed schedule.",
    )
    parser.add_argument(
        "--curriculum-threshold",
        type=float,
        default=0.5,
        help="Loss threshold to expand horizon in auto-curriculum mode.",
    )
    parser.add_argument(
        "--train-end",
        type=float,
        default=50.0,
        help="Final in-sample year (<= t_max) used for training loss; later times are treated as out-of-sample.",
    )
    parser.add_argument("--traj-plot", type=str, default=None, help="Optional explicit path for trajectory plot.")
    parser.add_argument("--phi-plot", type=str, default=None, help="Optional explicit path for phi plot.")
    parser.add_argument(
        "--r-plot",
        type=str,
        default=None,
        help="Optional explicit path for learned vs true r_i diagnostics.",
    )
    parser.add_argument(
        "--stagnation-epochs",
        type=int,
        default=50,
        help="Force curriculum increase if loss hasn't improved for this many epochs.",
    )
    parser.add_argument("--exp-root", type=str, default="experiments", help="Directory to store experiment outputs.")
    parser.add_argument(
        "--exp-prefix", type=str, default="GLV_learning_micro", help="Prefix for experiment folder names."
    )
    parser.add_argument(
        "--load-exp-dir",
        type=str,
        default=None,
        help="Path to an existing experiment directory whose model weights should be loaded before training.",
    )
    args = parser.parse_args()
    device = torch.device(args.device)

    train_end = min(max(args.train_end, 0.0), args.t_max)
    if train_end <= 0:
        raise ValueError("--train-end must be positive.")

    exp_root = Path(args.exp_root)
    exp_root.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y_%m_%d_%H:%M:%S")
    exp_dir = exp_root / f"{args.exp_prefix}_{timestamp}"
    exp_dir.mkdir(parents=True, exist_ok=False)

    traj_plot_path = Path(args.traj_plot) if args.traj_plot else exp_dir / "trajectory.png"
    phi_plot_path = Path(args.phi_plot) if args.phi_plot else exp_dir / "phi.png"
    r_plot_path = Path(args.r_plot) if args.r_plot else exp_dir / "r_progress.png"
    traj_plot_path.parent.mkdir(parents=True, exist_ok=True)
    phi_plot_path.parent.mkdir(parents=True, exist_ok=True)
    r_plot_path.parent.mkdir(parents=True, exist_ok=True)
    args.traj_plot = str(traj_plot_path)
    args.phi_plot = str(phi_plot_path)
    args.r_plot = str(r_plot_path)

    torch.manual_seed(0)

    r = torch.tensor([0.03, 0.08, 0.05, 0.04, 0.01], device=device)
    A = torch.zeros(5, 5, device=device)
    A.fill_(0.0)
    A.fill_diagonal_(-0.001)
    A[1, 0] = 0.004
    A[0, 1] = -0.005
    A[1, 4] = -0.010
    A[2, 4] = -0.015
    params = ThreeBodyParams(r=r, A=A)

    X0 = torch.tensor([100.0, 2.0, 5.0, 1.0, 8.0], device=device)
    times = torch.linspace(0.0, args.t_max, args.steps + 1, device=device)
    with torch.no_grad():
        true_traj = simulate_true(params, X0, times)

    curriculum_T = max(1.0, min(args.curriculum_start, train_end))

    phi_self = PhiSelf(r).to(device)
    phi_pair = PhiPair().to(device)
    if args.load_exp_dir:
        load_dir = Path(args.load_exp_dir)
        state_path = load_dir / "model.pt"
        if not state_path.exists():
            raise FileNotFoundError(f"Could not find pretrained model at {state_path}")
        state = torch.load(state_path, map_location=device)
        phi_self.load_state_dict(state["phi_self"])
        phi_pair.load_state_dict(state["phi_pair"])
        print(f"[INFO] Loaded pretrained weights from {state_path}")
    params_list = list(phi_self.parameters())
    optimizer = optim.AdamW(params_list, lr=args.lr, weight_decay=args.weight_decay)
    scheduler = None
    if args.cyclical_max_lr is not None:
        scheduler = optim.lr_scheduler.CyclicLR(
            optimizer,
            base_lr=args.lr,
            max_lr=args.cyclical_max_lr,
            step_size_up=max(1, args.cyclical_step),
            mode="triangular",
            cycle_momentum=False,
        )
    if args.cosine_min_lr is not None:
        if scheduler is not None:
            raise ValueError("Cannot enable both CyclicLR and CosineAnnealingLR simultaneously.")
        t_max = args.cosine_tmax if args.cosine_tmax is not None else args.epochs
        if t_max <= 0:
            raise ValueError("--cosine-tmax must be positive.")
        scheduler = optim.lr_scheduler.CosineAnnealingLR(
            optimizer,
            T_max=t_max,
            eta_min=args.cosine_min_lr,
        )

    best_loss = float("inf")
    last_improve_epoch = 0
    history = []
    progress_bar = tqdm(range(1, args.epochs + 1), desc="Training", ncols=140)
    for epoch in progress_bar:
        optimizer.zero_grad()

        # determine horizon slice
        current_T = min(curriculum_T, train_end)
        mask = times <= current_T + 1e-9
        times_slice = times[mask]
        if times_slice.shape[0] < 2:
            times_slice = times[:2]
        true_slice = true_traj[mask]

        pred_traj = rollout_model(phi_self, phi_pair, params, X0, times_slice)
        if torch.isnan(pred_traj).any():
            raise RuntimeError("NaN encountered in predicted trajectory.")
        diff = pred_traj - true_slice
        loss_traj = diff.abs().mean(dim=0).mean()
        if torch.isnan(loss_traj):
            raise RuntimeError("NaN in trajectory loss.")

        # Regularizers enforce zero boundaries
        reg_self = torch.tensor(0.0, device=device)
        reg_pair = torch.tensor(0.0, device=device)

        loss = loss_traj
        if torch.isnan(loss):
            raise RuntimeError("NaN in overall loss.")
        loss.backward()
        if args.grad_clip > 0:
            clip_grad_norm_(params_list, args.grad_clip)
        optimizer.step()
        if scheduler is not None:
            scheduler.step()

        current_lr = optimizer.param_groups[0]["lr"]
        progress_bar.set_postfix(
            {
                "loss": f"{loss.item():.4f}",
                "T": f"{curriculum_T:.3f} years",
                "reg": f"{reg_self.item()+reg_pair.item():.4f}",
                "lr": f"{current_lr:.4e}",
                "last_improve_epoch": f"{last_improve_epoch}",
            }
        )

        history.append(
            {
                "epoch": epoch,
                "loss": float(loss.item()),
                "loss_traj": float(loss_traj.item()),
                "reg_self": float(reg_self.item()),
                "reg_pair": float(reg_pair.item()),
                "lr": float(current_lr),
                "curriculum_T": float(curriculum_T),
                "r": phi_self.effective_r().detach().cpu().tolist(),
            }
        )

        if loss_traj.item() + 1e-6 < best_loss:
            best_loss = loss_traj.item()
            last_improve_epoch = epoch

        should_increase = False
        if args.curriculum_auto:
            if loss_traj.item() <= args.curriculum_threshold:
                should_increase = True
        else:
            if epoch % max(1, args.curriculum_period) == 0:
                should_increase = True

        if (epoch - last_improve_epoch) >= args.stagnation_epochs:
            should_increase = True
            last_improve_epoch = epoch
            

        if should_increase and curriculum_T < train_end:
            curriculum_T = min(train_end, curriculum_T + args.curriculum_increment)

    # Plot comparison
    pred_traj = rollout_model(phi_self, phi_pair, params, X0, times).detach().cpu()
    true_cpu = true_traj.detach().cpu()
    times_cpu = times.detach().cpu()

    fig, ax = plt.subplots(figsize=(10, 6))
    colors = ["#1b9e77", "#d95f02", "#7570b3", "#e7298a", "#66a61e"]
    faction_names = ["Earth", "Fleet", "Wallfacers", "Escapism", "ETO"]
    for i, (name, color) in enumerate(zip(faction_names, colors)):
        ax.plot(times_cpu, true_cpu[:, i], color=color, label=f"{name} (true)")
        ax.plot(
            times_cpu,
            pred_traj[:, i],
            color=color,
            linestyle="--",
            marker="o",
            markevery=max(1, len(times_cpu) // 25),
            markersize=3.0,
            label=f"{name} (learned)",
        )
    ax.axvspan(times_cpu[0], train_end, facecolor="#d9f0a3", alpha=0.25)
    ax.axvspan(train_end, times_cpu[-1], facecolor="#fdd0a2", alpha=0.18)
    ax.axvline(train_end, color="black", linestyle=":", linewidth=1.5)
    ylim = ax.get_ylim()
    span = times_cpu[-1] - times_cpu[0]
    ax.text(
        train_end / 2,
        ylim[1] - 0.08 * (ylim[1] - ylim[0]),
        "Training window",
        color="#386cb0",
        ha="center",
        va="center",
        fontsize=10,
    )
    ax.text(
        train_end + 0.02 * span,
        ylim[1] - 0.08 * (ylim[1] - ylim[0]),
        "Out-of-sample",
        color="#7f2704",
        ha="left",
        va="center",
        fontsize=10,
    )
    ax.set_xlabel("Years since First Contact")
    ax.set_ylabel("Capacity")
    ax.set_title("GLV Learning Micro: True vs Learned Trajectories")
    combined_handles = []
    combined_labels = []
    line_handles, line_labels = ax.get_legend_handles_labels()
    combined_handles.extend(line_handles)
    combined_labels.extend(line_labels)
    region_handles = [
        Patch(facecolor="#d9f0a3", alpha=0.25, label="Training"),
        Patch(facecolor="#fdd0a2", alpha=0.18, label="Out-of-sample"),
    ]
    for h in region_handles:
        combined_handles.append(h)
        combined_labels.append(h.get_label())
    if ax.legend_ is not None:
        ax.legend_.remove()
    fig.legend(
        combined_handles,
        combined_labels,
        loc="lower center",
        ncol=3,
        fontsize=8,
        frameon=False,
        bbox_to_anchor=(0.5, -0.04),
    )
    fig.tight_layout(rect=[0, 0.05, 1, 1])
    fig.savefig(traj_plot_path, dpi=200)
    print(f"[INFO] Saved trajectory comparison plot to {traj_plot_path}")

    # Plot phi_self / phi_pair slices
    xi = torch.linspace(0, 120, 200, device=device)
    S_samples = [0.6, 1.0, 1.2]
    eff_r = phi_self.effective_r().detach().cpu()
    plt.figure(figsize=(10, 5))
    for idx, name in enumerate(faction_names):
        for s_val in S_samples:
            phi_vals = xi.cpu() * (eff_r[idx].item() * s_val)
            plt.plot(
                xi.cpu(),
                phi_vals,
                label=f"{name}, S={s_val:.1f}",
            )
    plt.xlabel("x_i")
    plt.ylabel("phi_self")
    plt.title("Explicit phi_self slices")
    plt.legend(fontsize=7, ncol=2)
    plt.tight_layout()

    plt.figure(figsize=(10, 5))
    xj_samples = torch.tensor([10.0, 40.0, 80.0], device=device)
    for xj in xj_samples:
        with torch.no_grad():
            phi_vals = phi_pair(xi, torch.full_like(xi, xj)).cpu()
        plt.plot(xi.cpu(), phi_vals, label=f"x_j={xj.item():.0f}")
    plt.xlabel("x_i")
    plt.ylabel("phi_pair(x_i, x_j)")
    plt.title("Learned phi_pair slices")
    plt.legend()
    plt.tight_layout()
    plt.savefig(phi_plot_path, dpi=200)
    print(f"[INFO] Saved phi function plots to {phi_plot_path}")

    # Plot learned r_i trajectories versus ground truth r_i
    epochs_arr = np.array([entry["epoch"] for entry in history])
    r_history = np.array([entry["r"] for entry in history])
    true_r = params.r.detach().cpu().numpy()
    plt.figure(figsize=(9, 5))
    for idx, (name, color) in enumerate(zip(faction_names, colors)):
        plt.plot(epochs_arr, r_history[:, idx], color=color, label=f"{name} learned $r_i$")
        plt.hlines(
            true_r[idx],
            epochs_arr[0],
            epochs_arr[-1],
            colors=color,
            linestyles=":",
            linewidth=1.2,
            label=f"{name} true $r_i$",
        )
    plt.xlabel("Epoch")
    plt.ylabel(r"Growth rate $r_i$")
    plt.title("Learned vs true $r_i$ across training")
    plt.legend(ncol=2, fontsize=8)
    plt.tight_layout()
    plt.savefig(r_plot_path, dpi=200)
    print(f"[INFO] Saved r_i comparison plot to {r_plot_path}")

    np.save(exp_dir / "times.npy", times_cpu.numpy())
    np.save(exp_dir / "true_traj.npy", true_cpu.numpy())
    np.save(exp_dir / "pred_traj.npy", pred_traj.numpy())
    torch.save({"phi_self": phi_self.state_dict(), "phi_pair": phi_pair.state_dict()}, exp_dir / "model.pt")

    history_path = exp_dir / "history.json"
    with history_path.open("w") as f_hist:
        json.dump(history, f_hist, indent=2)

    args_dict = vars(args).copy()
    args_dict.update(
        {
            "traj_plot": str(traj_plot_path),
            "phi_plot": str(phi_plot_path),
            "r_plot": str(r_plot_path),
            "exp_dir": str(exp_dir),
        }
    )
    config = {
        "timestamp": timestamp,
        "args": args_dict,
        "best_traj_loss": best_loss,
        "final_curriculum_T": curriculum_T,
        "loaded_from": args.load_exp_dir,
    }
    with (exp_dir / "config.json").open("w") as f_cfg:
        json.dump(config, f_cfg, indent=2)

    command_text = " ".join([sys.executable] + sys.argv)
    with (exp_dir / "command.txt").open("w") as f_cmd:
        f_cmd.write("Full command:\n")
        f_cmd.write(command_text + "\n")
        f_cmd.write("\nArguments:\n")
        for key in sorted(args_dict):
            f_cmd.write(f"{key}: {args_dict[key]}\n")

    try:
        shutil.copy(Path(__file__), exp_dir / Path(__file__).name)
    except Exception as copy_err:
        print(f"[WARN] Failed to copy script to experiment folder: {copy_err}")

    print(f"[INFO] Experiment artifacts saved to {exp_dir}")

if __name__ == "__main__":
    main()

